// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dotnetapitest.Migrations
{
    [DbContext(typeof(ItemsContext))]
    partial class ItemsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SKU")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Description = "Dining Table",
                            SKU = 665544332
                        },
                        new
                        {
                            ItemId = 2,
                            Description = "Dining Table",
                            SKU = 665544332
                        },
                        new
                        {
                            ItemId = 3,
                            Description = "Dining Table",
                            SKU = 665544332
                        },
                        new
                        {
                            ItemId = 4,
                            Description = "Dining Table",
                            SKU = 665544332
                        },
                        new
                        {
                            ItemId = 5,
                            Description = "Dining Table",
                            SKU = 665544332
                        },
                        new
                        {
                            ItemId = 6,
                            Description = "Dining Table",
                            SKU = 665544332
                        },
                        new
                        {
                            ItemId = 7,
                            Description = "Dining Table",
                            SKU = 665544332
                        },
                        new
                        {
                            ItemId = 8,
                            Description = "Dining Table",
                            SKU = 665544332
                        },
                        new
                        {
                            ItemId = 9,
                            Description = "Dining Table",
                            SKU = 665544332
                        },
                        new
                        {
                            ItemId = 10,
                            Description = "Dining Table",
                            SKU = 665544332
                        },
                        new
                        {
                            ItemId = 11,
                            Description = "Dining Chair",
                            SKU = 665544331
                        },
                        new
                        {
                            ItemId = 12,
                            Description = "Dining Chair",
                            SKU = 665544331
                        },
                        new
                        {
                            ItemId = 13,
                            Description = "Dining Chair",
                            SKU = 665544331
                        },
                        new
                        {
                            ItemId = 14,
                            Description = "Dining Chair",
                            SKU = 665544331
                        },
                        new
                        {
                            ItemId = 15,
                            Description = "Dining Chair",
                            SKU = 665544331
                        },
                        new
                        {
                            ItemId = 16,
                            Description = "Dining Chair",
                            SKU = 665544331
                        },
                        new
                        {
                            ItemId = 17,
                            Description = "Dining Chair",
                            SKU = 665544331
                        },
                        new
                        {
                            ItemId = 18,
                            Description = "Dining Chair",
                            SKU = 665544331
                        },
                        new
                        {
                            ItemId = 19,
                            Description = "Dining Chair",
                            SKU = 665544331
                        },
                        new
                        {
                            ItemId = 20,
                            Description = "Dining Chair",
                            SKU = 665544331
                        },
                        new
                        {
                            ItemId = 21,
                            Description = "Sofa",
                            SKU = 665544333
                        },
                        new
                        {
                            ItemId = 22,
                            Description = "Sofa",
                            SKU = 665544333
                        },
                        new
                        {
                            ItemId = 23,
                            Description = "Sofa",
                            SKU = 665544333
                        },
                        new
                        {
                            ItemId = 24,
                            Description = "Sofa",
                            SKU = 665544333
                        },
                        new
                        {
                            ItemId = 25,
                            Description = "Sofa",
                            SKU = 665544333
                        },
                        new
                        {
                            ItemId = 26,
                            Description = "Sofa",
                            SKU = 665544333
                        },
                        new
                        {
                            ItemId = 27,
                            Description = "Sofa",
                            SKU = 665544333
                        },
                        new
                        {
                            ItemId = 28,
                            Description = "Sofa",
                            SKU = 665544333
                        },
                        new
                        {
                            ItemId = 29,
                            Description = "Sofa",
                            SKU = 665544333
                        },
                        new
                        {
                            ItemId = 30,
                            Description = "Sofa",
                            SKU = 665544333
                        },
                        new
                        {
                            ItemId = 31,
                            Description = "Loveseat",
                            SKU = 665544334
                        },
                        new
                        {
                            ItemId = 32,
                            Description = "Loveseat",
                            SKU = 665544334
                        },
                        new
                        {
                            ItemId = 33,
                            Description = "Loveseat",
                            SKU = 665544334
                        },
                        new
                        {
                            ItemId = 34,
                            Description = "Loveseat",
                            SKU = 665544334
                        },
                        new
                        {
                            ItemId = 35,
                            Description = "Loveseat",
                            SKU = 665544334
                        },
                        new
                        {
                            ItemId = 36,
                            Description = "Loveseat",
                            SKU = 665544334
                        },
                        new
                        {
                            ItemId = 37,
                            Description = "Loveseat",
                            SKU = 665544334
                        },
                        new
                        {
                            ItemId = 38,
                            Description = "Loveseat",
                            SKU = 665544334
                        },
                        new
                        {
                            ItemId = 39,
                            Description = "Loveseat",
                            SKU = 665544334
                        },
                        new
                        {
                            ItemId = 40,
                            Description = "Loveseat",
                            SKU = 665544334
                        },
                        new
                        {
                            ItemId = 41,
                            Description = "Chair",
                            SKU = 665544335
                        },
                        new
                        {
                            ItemId = 42,
                            Description = "Chair",
                            SKU = 665544335
                        },
                        new
                        {
                            ItemId = 43,
                            Description = "Chair",
                            SKU = 665544335
                        },
                        new
                        {
                            ItemId = 44,
                            Description = "Chair",
                            SKU = 665544335
                        },
                        new
                        {
                            ItemId = 45,
                            Description = "Chair",
                            SKU = 665544335
                        },
                        new
                        {
                            ItemId = 46,
                            Description = "Chair",
                            SKU = 665544335
                        },
                        new
                        {
                            ItemId = 47,
                            Description = "Chair",
                            SKU = 665544335
                        },
                        new
                        {
                            ItemId = 48,
                            Description = "Chair",
                            SKU = 665544335
                        },
                        new
                        {
                            ItemId = 49,
                            Description = "Chair",
                            SKU = 665544335
                        },
                        new
                        {
                            ItemId = 50,
                            Description = "Chair",
                            SKU = 665544335
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
